-- INITIAL DATA FOR CURRENCY PROPERTIES
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AFN','Afghanistan Afghani','afghanistan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ALL','Albanian Lek','albania',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DZD','Algerian Dinar','algeria',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','american_samoa',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','andorra',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AOA','Angolan Kwanza','angola',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','anguilla',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','antarctica',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','antigua_and_barbuda',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ARS','Argentine Peso','argentina',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AMD','Armenian Dram','armenia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AWG','Aruban Guilder','aruba',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','australia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','austria',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AZN','Azerbaijan New Manat','azerbaijan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BSD','Bahamian Dollar','bahamas',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BHD','Bahraini Dinar','bahrain',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BDT','Bangladeshi Taka','bangladesh',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BBD','Barbados Dollar','barbados',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BYR','Belarussian Ruble','belarus',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','belgium',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BZD','Belize Dollar','belize',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','benin',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BMD','Bermudian Dollar','bermuda',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BTN','Bhutan Ngultrum','bhutan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BOB','Boliviano','bolivia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BAM','Marka','bosnia_and_herzegovina',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BWP','Botswana Pula','botswana',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NOK','Norwegian Krone','bouvet island',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BRL','Brazilian Real','brazil',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','british indian ocean territory',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BND','Brunei Dollar','brunei darussalam',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BGN','Bulgarian Lev','bulgaria',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','burkina faso',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('BIF','Burundi Franc','burundi',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KHR','Kampuchean Riel','cambodia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','cameroon',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CAD','Canadian Dollar','canada',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CVE','Cape Verde Escudo','cape verde',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KYD','Cayman Islands Dollar','cayman islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','central african republic',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','chad',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CLP','Chilean Peso','chile',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CNY','Yuan Renminbi','china',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','christmas island',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','cocos(keeling) islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('COP','Colombian Peso','colombia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KMF','Comoros Franc','comoros',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','congo',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CDF','Francs','congo, dem. republic',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NZD','New Zealand Dollar','cook islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CRC','Costa Rican Colon','costa rica',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('HRK','Croatian Kuna','croatia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CUP','Cuban Peso','cuba',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','cyprus',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CZK','Czech Koruna','czech rep.',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DKK','Danish Krone','denmark',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DJF','Djibouti Franc','djibouti',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','dominica',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DOP','Dominican Peso','dominican republic',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ECS','Ecuador Sucre','ecuador',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EGP','Egyptian Pound','egypt',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SVC','El Salvador Colon','el salvador',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','equatorial guinea',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ERN','Eritrean Nakfa','eritrea',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','estonia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ETB','Ethiopian Birr','ethiopia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','european union',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('FKP','Falkland Islands Pound','falkland islands(malvinas)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DKK','Danish Krone','faroe islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('FJD','Fiji Dollar','fiji',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','finland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','france',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','french guiana',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','french southern territories',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XAF','CFA Franc BEAC','gabon',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GMD','Gambian Dalasi','gambia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GEL','Georgian Lari','georgia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','germany',1);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GHS','Ghanaian Cedi','ghana',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GIP','Gibraltar Pound','gibraltar',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GBP','Pound Sterling','great britain',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','greece',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('DKK','Danish Krone','greenland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Carribean Dollar','grenada',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','guadeloupe(french)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','guam(usa)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GNF','Guinea Franc','guinea',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GWP','Guinea-Bissau Peso','guinea bissau',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GYD','Guyana Dollar','guyana',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('HTG','Haitian Gourde','haiti',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','heard island and mcdonald islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('HNL','Honduran Lempira','honduras',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('HKD','Hong Kong Dollar','hong kong',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('HUF','Hungarian Forint','hungary',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ISK','Iceland Krona','iceland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('INR','Indian Rupee','india',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('IDR','Indonesian Rupiah','indonesia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('IRR','Iranian Rial','iran',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('IQD','Iraqi Dinar','iraq',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','ireland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GBP','Pound Sterling','isle of man',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ILS','Israeli New Shekel','israel',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','italy',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','ivory coast',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('JMD','Jamaican Dollar','jamaica',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('JPY','Japanese Yen','japan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GBP','Pound Sterling','jersey',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('JOD','Jordanian Dinar','jordan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KZT','Kazakhstan Tenge','kazakhstan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KES','Kenyan Shilling','kenya',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','kiribati',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KPW','North Korean Won','korea-north',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KRW','Korean Won','korea-south',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KWD','Kuwaiti Dinar','kuwait',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('KGS','Som','kyrgyzstan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LAK','Lao Kip','laos',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LVL','Latvian Lats','latvia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LBP','Lebanese Pound','lebanon',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LSL','Lesotho Loti','lesotho',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LRD','Liberian Dollar','liberia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LYD','Libyan Dinar','libya',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CHF','Swiss Franc','liechtenstein',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LTL','Lithuanian Litas','lithuania',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','luxembourg',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MOP','Macau Pataca','macau',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MKD','Denar','macedonia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MWK','Malawi Kwacha','malawi',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MYR','Malaysian Ringgit','malaysia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MVR','Maldive Rufiyaa','maldives',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','mali',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','malta',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','marshall islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','martinique(french)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MRO','Mauritanian Ouguiya','mauritania',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MUR','Mauritius Rupee','mauritius',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','mayotte',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MXN','Mexican Nuevo Peso','mexico',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','micronesia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MDL','Moldovan Leu','moldova',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','monaco',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MNT','Mongolian Tugrik','mongolia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','montenegro',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','montserrat',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MAD','Moroccan Dirham','morocco',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MZN','Mozambique Metical','mozambique',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MMK','Myanmar Kyat','myanmar',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NAD','Namibian Dollar','namibia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','nauru',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NPR','Nepalese Rupee','nepal',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','netherlands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ANG','Netherlands Antillean Guilder','netherlands antilles',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XPF','CFP Franc','new caledonia(french)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NZD','New Zealand Dollar','new zealand',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NIO','Nicaraguan Cordoba Oro','nicaragua',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','niger',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NGN','Nigerian Naira','nigeria',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NZD','New Zealand Dollar','niue',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','norfolk island',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','northern mariana islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NOK','Norwegian Krone','norway',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('OMR','Omani Rial','oman',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PKR','Pakistan Rupee','pakistan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','palau',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PAB','Panamanian Balboa','panama',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PGK','Papua New Guinea Kina','papua new guinea',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PYG','Paraguay Guarani','paraguay',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PEN','Peruvian Nuevo Sol','peru',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PHP','Philippine Peso','philippines',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NZD','New Zealand Dollar','pitcairn island',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('PLN','Polish Zloty','poland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XPF','CFP Franc','polynesia(french)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','portugal',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','puerto rico',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('QAR','Qatari Rial','qatar',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','reunion(french)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('RON','Romanian New Leu','romania',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('RUB','Russian Ruble','russia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('RWF','Rwanda Franc','rwanda',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SHP','St. Helena Pound','saint helena',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','saint kitts & nevis anguilla',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','saint lucia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','saint pierre and miquelon',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XCD','East Caribbean Dollar','saint vincent & grenadines',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('WST','Samoan Tala','samoa',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','san marino',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('STD','Dobra','sao tome and principe',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SAR','Saudi Riyal','saudi arabia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','senegal',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('RSD','Dinar','serbia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SCR','Seychelles Rupee','seychelles',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SLL','Sierra Leone Leone','sierra leone',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SGD','Singapore Dollar','singapore',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','slovakia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','slovenia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SBD','Solomon Islands Dollar','solomon islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SOS','Somali Shilling','somalia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ZAR','South African Rand','south africa',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GBP','Pound Sterling','south georgia & south sandwich islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SSP','South Sudan Pound','south sudan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','spain',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('LKR','Sri Lanka Rupee','sri lanka',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SDG','Sudanese Pound','sudan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SRD','Surinam Dollar','suriname',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NOK','Norwegian Krone','svalbard and jan mayen islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SZL','Swaziland Lilangeni','swaziland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SEK','Swedish Krona','sweden',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('CHF','Swiss Franc','switzerland',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('SYP','Syrian Pound','syria',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TWD','Taiwan Dollar','taiwan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TJS','Tajik Somoni','tajikistan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TZS','Tanzanian Shilling','tanzania',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('THB','Thai Baht','thailand',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XOF','CFA Franc BCEAO','togo',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('NZD','New Zealand Dollar','tokelau',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TOP','Tongan Paanga','tonga',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TTD','Trinidad and Tobago Dollar','trinidad and tobago',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TND','Tunisian Dollar','tunisia',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TRY','Turkish Lira','turkey',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('TMT','Manat','turkmenistan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','turks and caicos islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AUD','Australian Dollar','tuvalu',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('GBP','Pound Sterling','u.k.',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('UGX','Uganda Shilling','uganda',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('UAH','Ukraine Hryvnia','ukraine',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('AED','Arab Emirates Dirham','united arab emirates',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('UYU','Uruguayan Peso','uruguay',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','usa',1);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','usa minor outlying islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('UZS','Uzbekistan Sum','uzbekistan',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('VUV','Vanuatu Vatu','vanuatu',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('EUR','Euro','vatican',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('VEF','Venezuelan Bolivar','venezuela',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('VND','Vietnamese Dong','vietnam',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','virgin islands(british)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('USD','US Dollar','virgin islands(usa)',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('XPF','CFP Franc','wallis and futuna islands',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('MAD','Moroccan Dirham','western sahara',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('YER','Yemeni Rial','yemen',0);
INSERT INTO currency_property(currency_code,currency_name,currency_country,currency_enabled) VALUES('ZMW','Zambian Kwacha','zambia',0);